# Generated by Django 6.0.3 on 2026-03-12 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="description",
            new_name="content",
        ),
    ]
